min_chunk_length: 4.0
max_chunk_length: 4.0
return_fullseqs: false
wav_scale: 32767
batch_size: 512
var_batch_size: false
iters_per_epoch: 6.0
train_aug_cfg: conf/reverb_noise_aug.yaml
val_aug_cfg: conf/reverb_noise_aug.yaml
feats: fbank64_stmn_nb_16k.yaml
pool_net:
  pool_type: ch-wise-att-mean+stddev
  inner_feats: 32
embed_dim: 32
num_embed_layers: 1
hid_act: relu6
loss_type: arc-softmax
s: 30.0
margin: 0.3
margin_warmup_epochs: 30.0
dropout_rate: 0.0
in_feats: 64
resnet_type: lresnet34
in_channels: 1
conv_channels: 64
base_channels: 64
in_kernel_size: 3
in_stride: 1
in_norm: false
no_maxpool: true
optim:
  opt_type: adam
  lr: 0.02
  # lr: 0.01
  beta1: 0.9
  beta2: 0.95
  amsgrad: true
  weight_decay: 1e-5
lrsched:
  lrsch_type: exp_lr
  decay_rate: 0.5
  decay_steps: 8000
  hold_steps: 10000
  min_lr: 1.0e-05
  warmup_steps: 1000
  update_lr_on_opt_step: true
grad_acc_steps: 1
epochs: 70
log_interval: 100
use_tensorboard: false
use_wandb: false
wandb:
  mode: online
ddp_type: ddp
use_amp: true
swa_start: 0
swa_lr: 0.001
swa_anneal_epochs: 10
num_gpus: 4
